### ISSUE TITLE
semantics around the rules

### ISSUE THREAD

**Issue by arcman77** [eatnumber1/goal#203]
When you say `g('al') must return "gal".` 

Do you mean that the actual return value of function g is "gal" or do you mean that the string "gal" must be printed by the specified invocation of function g?

Cause I have something that does this:
![image](https://user-images.githubusercontent.com/19784185/43606829-54ef0e40-9651-11e8-8689-31fbfbb9db86.png)

**Comment by eatnumber1** [comment]
Rule 7 covers that:

"g()('al') may not print the string. If returning a string cannot be done
in your language, you should submit rationale as to why this is impossible
for a solution which prints a string to be accepted."
